CREATE TABLE IF NOT EXISTS users (
 telegramid INTEGER NOT NULL,
 lang TEXT DEFAULT NULL,
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 msgid INTEGER NOT NULL DEFAULT 0,
 view TEXT NOT NULL DEFAULT 'day',
 notif TEXT NOT NULL DEFAULT 'yes',
 isTester INTEGER NOT NULL DEFAULT 0,
 morningNotif TEXT DEFAULT 'yes',
 HWNotif TEXT DEFAULT 'yes',
 aiEnabled INT DEFAULT 1,
 lastReset DATE DEFAULT NULL,
 msgCount INT DEFAULT 0
);